### ISSUE TITLE
ncmdump may cut off a few milliseconds from the beginning of a mp3

### ISSUE THREAD

**Issue by xxoo** [haiyoune7/ncmdump#13]
it may has something to do with the cover I guess
the attached file can be used for reproducing the issue
[顶楼的马戏团 - 义务为豪大大鸡排所作个广告歌.ncm.zip](https://github.com/user-attachments/files/15777513/-.ncm.zip)

**Comment by iqiziqi** [comment]
You are right, i will fix this bug later.

**Comment by iqiziqi** [comment]
In my test, this bug is fixed by #14 .

**Comment by xxoo** [comment]
yes it works perfectly now
