### ISSUE TITLE
Converted filename cut off

### ISSUE THREAD

**Issue by PhyX-Meow** [haiyoune7/ncmdump#7]
Say converting `残酷な天使のテーゼ ＜Director's Edit. Version II＞.ncm`, ncmdump gives `残酷な天使のテーゼ ＜Director's Edit.flac`.
The filename string after second last `.` was lost.

The command line I use is
```
ncmdump.exe '.\残酷な天使のテーゼ ＜Director''s Edit. Version II＞.ncm'
```

**Comment by iqiziqi** [comment]
Thanks for your report. I reproduced this issue. It will be fix #8.
